name: CI Pipeline

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 실행
  pull_request:
    branches:
      - main # main 브랜치로의 풀 리퀘스트가 열릴 때 실행

jobs:
  test:
    runs-on: ubuntu-latest # 최신 우분투 환경에서 실행

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3 # GitHub Actions에서 제공하는 체크아웃 액션 사용

      - name: Node.js 설정
        uses: actions/setup-node@v3 # Node.js 환경 설정 액션 사용
        with:
          node-version: '16' # Node.js 버전 16 사용

      - name: 의존성 설치
        run: npm install # npm을 사용하여 의존성 설치

      - name: 테스트 실행
        run: npm test # npm을 사용하여 테스트 실행
